global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'webhook.site'
receivers:
- name: 'webhook.site'
  webhook_configs:
  - url: 'http://webhook'
