global:
  scrape_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-3-129-183-224.us-east-2.compute.amazonaws.com:9100']
  # - job_name: 'process_exporter'
  #   static_configs:
  #     - targets: ['podman:9256']

rule_files:
  - alert.rules